when:
  - event: manual
  - event: push
    branch: main

steps:
  - name: build-and-push-ghcr
    image: woodpeckerci/plugin-docker-buildx:6.1.1@sha256:9a22c00b4952e405d11e66d29772edbeb1f7b24f27f71cda251ecb838e725e86
    privileged: true
    settings:
      registry: ghcr.io
      repo: ghcr.io/isityael/chart-version-guard
      dockerfile: Dockerfile
      context: .
      tags:
        - "${CI_COMMIT_SHA:0:8}"
        - main
      logins:
        - registry: ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_token
        - registry: dhi.io
          username:
            from_secret: dhi_username
          password:
            from_secret: dhi_password
      provenance: mode=max
      buildkit_driveropt: network=host
      cache_from: 'type=registry\,ref=ghcr.io/isityael/chart-version-guard:buildcache'
      cache_to: 'type=registry,ref=ghcr.io/isityael/chart-version-guard:buildcache,mode=max,ignore-error=true'
