when:
  - event: pull_request
  - event: push
    branch: main

steps:
  - name: go-test
    image: dhi.io/golang:1.26.4-debian13-dev@sha256:69c8fbc3f16f53e69cedebcf97a644b4e63e5ef778854ab366467271f2a2bef2
    environment:
      DHI_USERNAME:
        from_secret: dhi_username
      DHI_PASSWORD:
        from_secret: dhi_password
    commands:
      - go test ./...
      - go vet ./...
      - test -z "$(gofmt -l .)"
