when:
  - event: pull_request
  - event: push
    branch: main

steps:
  - name: go-test
    image: dhi.io/golang:1.26.4-debian13-dev@sha256:c02293a491c454b4fa27653b9d1ff8991b7355ce7b71a9ff6bc6b827e3eb9379
    environment:
      DHI_USERNAME:
        from_secret: dhi_username
      DHI_PASSWORD:
        from_secret: dhi_password
    commands:
      - go test ./...
      - go vet ./...
      - test -z "$(gofmt -l .)"
