when:
  - event: pull_request
  - event: push
    branch: main

steps:
  - name: go-test
    image: dhi.io/golang:1.26.5-debian13-dev@sha256:1ef1aef62b8577699adccac73b6970b3ff893df89fdf57bf2cd0ce3b523724d1
    environment:
      DHI_USERNAME:
        from_secret: dhi_username
      DHI_PASSWORD:
        from_secret: dhi_password
    commands:
      - go test ./...
      - go vet ./...
      - test -z "$(gofmt -l .)"
